### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by FearlessPotatoKing** [joshuacant/undo_closed_tabs_menu#2]
Can you provide some instructions on how to go at installing this? I would love to use this with Tree Style Tabs addon on Firefox 58 and i've done a bit of coding here and there, but i'm not sure how to go about at exporting this as an addon or installing it.
Thank You!

**Comment by joshuacant** [comment]
I'll have these published on Mozilla's Addon site sometime before the release of Firefox 57. In the meantime, you can go to the release page: https://github.com/joshuacant/tst-closed_tabs_menu/releases and install the most recent xpi. It will ask permission to allow github to install an addon and then install just like normal.

Let me know if you run into any issues with it.
