### ISSUE TITLE
Make compatible with Tree Style Tab RainbowTabsFork

### ISSUE THREAD

**Issue by MurzNN** [joshuacant/undo_closed_tabs_menu#3]
Please make your extension (and others) compatible with Tree Style Tab fork with colored tabs https://addons.mozilla.org/ru/firefox/addon/tree-style-tab-rainbowtabsfork/

**Comment by joshuacant** [comment]
Sorry, but I don't have time to support a fork of TST. Someone could take my code and make their own fork, or you could even see if the Rainbow Tabs developer wanted to implement my code right into their TST fork.
