### ISSUE TITLE
Closed tabs should be appended to the general tabbar context menu as well

### ISSUE THREAD

**Issue by infinity0** [joshuacant/undo_closed_tabs_menu#4]
Hey, thanks for writing this, I found out about it after discussing it in https://github.com/piroor/treestyletab/issues/2038

I tried it out and it works nicely, however the "closed tabs" list is currently being shown only when right-clicking a specific tab. It would be nice if it was also shown when clicking on the tab-bar outside of a tab.

If I understand correctly, TST does not expose this in its API currently, so I've asked piroor to supply this functionality in https://github.com/piroor/treestyletab/issues/2038.

**Comment by joshuacant** [comment]
I wanted to add this, but discovered the same thing you did: That TST does not provide this functionality through its API.

If piroor enables support for adding to the non-tab-specific menu, I will add this feature.
