### ISSUE TITLE
Show more than 25 closed tabs

### ISSUE THREAD

**Issue by ReporterX** [joshuacant/undo_closed_tabs_menu#5]
Is it possible, or a hard limit?

If hard limit, is it possible to workaround it, like by creating an interface?

**Comment by joshuacant** [comment]
"It is read-only for WebExtension code, and is set to 25."
Source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/MAX_SESSION_RESULTS

The limit of 25 is hard coded into Firefox itself. I also wish I could set it higher. You'd have to ask Mozilla to support a higher limit.

**Comment by ReporterX** [comment]
> 
> 
> "It is read-only for WebExtension code, and is set to 25."
> Source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/MAX_SESSION_RESULTS
> 
> The limit of 25 is hard coded into Firefox itself. I also wish I could set it higher. You'd have to ask Mozilla to support a higher limit.

Thanks for the confirmation.

I'm going to edit the file just to bypass the limit. Is it possible?  
Do you know which file exactly stores this value?

Thank you.
