### ISSUE TITLE
Broken by Firefox 72

### ISSUE THREAD

**Issue by McBobb** [joshuacant/undo_closed_tabs_menu#6]
Thank-you so much for creating this. I loved it very much, but as soon as I installed FF 72.0, it broke. The "Undo Closed Tab >" entry is completely missing from the right-click menu of tabs, even when tabs have been closed in that session.

The changes in about:config are still there, and I've eliminated all other possible interfering factors except the new release of Firefox itself.

As you may know, Mozilla also broke "Tabs at Bottom" userChrome.css, so I'm not surprised by this, but while I've found a fix for the "Tabs at Bottom" issue, I have not been able to find one to fix your extremely (I would hazard to say Essential) addon?

I appreciate that you are a volunteer working on your own time, solely to benefit the global community of Firefox users, but if you can find a solution, or suggest a place to start looking for a solution myself, I would greatly appreciate it.

Thanks.

Troubleshooting Info

Application Basics
------------------

Name: Firefox
Version: 72.0.1
Build ID: 20200107212822
Update Channel: release
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0
OS: Windows_NT 10.0
Launcher Process: Enabled
Multiprocess Windows: 1/1 Enabled by default
Remote Processes: 6
Enterprise Policies: Inactive
Google Location Service Key: Found
Google Safebrowsing Key: Found
Mozilla Location Service Key: Found
Safe Mode: false

Crash Reports for the Last 3 Days
---------------------------------

Firefox Features
----------------

Name: DoH Roll-Out
Version: 1.3.0
ID: doh-rollout@mozilla.org

Name: Firefox Screenshots
Version: 39.0.0
ID: screenshots@mozilla.org

Name: Form Autofill
Version: 1.0
ID: formautofill@mozilla.org

Name: Web Compat
Version: 6.4.0
ID: webcompat@mozilla.org

Name: WebCompat Reporter
Version: 1.1.0
ID: webcompat-reporter@mozilla.org

Remote Processes
----------------

Type: Web Content
Count: 4 / 4

Type: Extension
Count: 1

Type: GPU
Count: 1

Extensions
----------

Name: Adblock for Youtube™
Version: 2.0.2
Enabled: true
ID: {94036cd5-1829-4480-ab0b-e2455deafb9c}

Name: Adblock Plus - free ad blocker
Version: 3.7
Enabled: true
ID: {d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}

Name: AdBlocker for YouTube™
Version: 0.3.2
Enabled: true
ID: jid1-q4sG8pYhq8KGHs@jetpack

Name: AddToAny: Share Anywhere
Version: 3.3.0
Enabled: true
ID: {35d49e56-0142-4a7b-82a8-6ace7d28ff92}

Name: AdGuard AdBlocker
Version: 3.3.8
Enabled: true
ID: adguardadblocker@adguard.com

Name: Amazon.co.uk
Version: 1.1
Enabled: true
ID: amazon@search.mozilla.org

Name: Ant Video downloader
Version: 4.4
Enabled: true
ID: anttoolbar@ant.com

Name: Bing
Version: 1.0
Enabled: true
ID: bing@search.mozilla.org

Name: Bookmark Tab Here
Version: 1.0
Enabled: true
ID: {bc21b9a1-3ad6-4b00-bca4-ef5b7e21253b}

Name: Bookmarks Organizer
Version: 3.1.0
Enabled: true
ID: bookmarksorganizer@agenedia.com

Name: Clear Site Cookies
Version: 1.2
Enabled: true
ID: clearsitecookie@mhillsystem.com

Name: Dark Background and Light Text
Version: 0.7.2
Enabled: true
ID: jid1-QoFqdK4qzUfGWQ@jetpack

Name: Delete History
Version: 1.1
Enabled: true
ID: history-delete@dsrini-open.github.com

Name: Disconnect
Version: 5.19.3
Enabled: true
ID: 2.0@disconnect.me

Name: Don't Fuck With Paste
Version: 2.3.1
Enabled: true
ID: DontFuckWithPaste@raim.ist

Name: Download all Images
Version: 0.6.6
Enabled: true
ID: {32af1358-428a-446d-873e-5f8eb5f2a72e}

Name: Download Image from Context Menu
Version: 0.2.2
Enabled: true
ID: {5ff1cbc2-229c-4f3f-ac0e-884fbc12670b}

Name: Download Manager (S3)
Version: 5.12
Enabled: true
ID: s3download@statusbar

Name: Download with Free Download Manager (FDM)
Version: 0.1.7
Enabled: true
ID: {1fb1ffdc-b95d-451e-be52-7303adf9a0d3}

Name: DuckDuckGo
Version: 1.0
Enabled: true
ID: ddg@search.mozilla.org

Name: easyGestures N
Version: 6.3
Enabled: true
ID: easyGesturesN@ngdeleito.eu

Name: eBay
Version: 1.0
Enabled: true
ID: ebay@search.mozilla.org

Name: Element Blocker
Version: 1.3
Enabled: true
ID: element-blocker@lukepeters.me

Name: Element-Hider
Version: 1.1
Enabled: true
ID: {402b80e2-c899-4152-9814-f17cd6c753af}

Name: Emoji Keyboard - Emojis For Firefox
Version: 4.2.4
Enabled: true
ID: @emojikeyboard

Name: Empty Cache Button
Version: 3.4
Enabled: true
ID: {4cc4a13b-94a6-7568-370d-5f9de54a9c7f}

Name: Enhancer for YouTube™
Version: 2.0.99
Enabled: true
ID: enhancerforyoutube@maximerf.addons.mozilla.org

Name: Find & Replace for Text Editing
Version: 1.3.17
Enabled: true
ID: {ad1a1412-512a-4955-8bea-3ac63a5d970b}

Name: Fixed Zoom
Version: 2.1.5
Enabled: true
ID: {a655a6b2-69a5-40de-a3b8-3f7f200c95a7}

Name: FoxReplace
Version: 2.3.1
Enabled: true
ID: fox@replace.fx

Name: Free Download Manager
Version: 3.0.41
Enabled: true
ID: fdm_ffext2@freedownloadmanager.org

Name: Go to Top of Page Button
Version: 1.3
Enabled: true
ID: top-page-single@codefisher.org

Name: Google
Version: 1.0
Enabled: true
ID: google@search.mozilla.org

Name: Greasemonkey
Version: 4.9
Enabled: true
ID: {e4a8a97b-f2ed-450b-b12d-ee082ba24781}

Name: Happy Right-Click
Version: 1.1.0
Enabled: true
ID: {dd10d63e-3096-4492-ab0e-5edcf4baf988}

Name: Hide Fixed Elements
Version: 1.2
Enabled: true
ID: hidefixedelements@commonground.systems

Name: HTML Content Blocker
Version: 0.1.8
Enabled: true
ID: jid1-p8wT8wUxc4KaJo@jetpack

Name: Image Downloader
Version: 0.1.1
Enabled: true
ID: {589e6459-3d56-49b4-9b3d-6e4b7ef16940}

Name: ImTranslator: Translator, Dictionary, TTS
Version: 15.41
Enabled: true
ID: {9AA46F4F-4DC7-4c06-97AF-5035170634FE}

Name: Kee - Password Manager
Version: 3.2.7
Enabled: true
ID: keefox@chris.tomlinson

Name: LoadTabOnSelect3
Version: 1.2019.926.0
Enabled: true
ID: {85d2532b-a793-4048-8ef4-713af1ff320d}

Name: Media Panel
Version: 2.6
Enabled: true
ID: {68d048f4-9449-4c97-8425-6dac7f743b14}

Name: Merge Windows
Version: 1.0
Enabled: true
ID: {07532c74-a5e9-491b-82d6-e55bc0e03d67}

Name: Move Tabs
Version: 0.0.2
Enabled: true
ID: {cb327223-fe49-4d02-8233-134198263b81}

Name: Multiple File Downloader
Version: 1.5.0
Enabled: true
ID: {3f1d5914-65d6-4344-985b-2c6c28a40398}

Name: NoScript
Version: 11.0.11
Enabled: true
ID: {73a6fe31-595d-460b-a920-fcc0f8843232}

Name: Official Media Bias Fact Check Icon
Version: 1.7.1
Enabled: true
ID: {6ba00d80-d8f3-4e1a-bc70-e1b6c64ae4a0}

Name: Open Page in Private Window
Version: 1.1.1
Enabled: true
ID: open-page-in-private-window@cpeterso.com

Name: OSINT - Open Selection In New Tab
Version: 1.0
Enabled: true
ID: {ae152399-14cd-4330-9baf-1f233ee70d62}

Name: Popup Bookmarks
Version: 1.4.1
Enabled: true
ID: addon_popup_bookmarks@crossblade.her.jp

Name: Restart Browser
Version: 1.2
Enabled: true
ID: Restartfirefox@vazextension.com

Name: Search Engine Ad Remover
Version: 1.1.3
Enabled: true
ID: @searchengineadremover

Name: Show/Hide passwords
Version: 0.4
Enabled: true
ID: shpassword@shpassword.fr

Name: Simple Close Tab button
Version: 1.2
Enabled: true
ID: {fe8cab45-aaee-45f8-8765-781e0ebea300}

Name: Simple Form Fill
Version: 2.1.6
Enabled: true
ID: simpleformfill@sblask

Name: Smart Tab Mute
Version: 1.0.1.1
Enabled: true
ID: smart-tab-mute@die-antwort.eu

Name: Snap Links
Version: 3.1.7
Enabled: true
ID: snaplinks@snaplinks.mozdev.org

Name: Stylus
Version: 1.5.6
Enabled: true
ID: {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}

Name: Tab Close Button
Version: 1.4
Enabled: true
ID: {ab300b16-85cb-4380-bdb8-fa96903f2b3c}

Name: Tab Session Manager
Version: 5.2.0
Enabled: true
ID: Tab-Session-Manager@sienori

Name: Text Link
Version: 6.0.3
Enabled: true
ID: {54BB9F3F-07E5-486c-9B39-C7398B99391C}

Name: Textarea Cache
Version: 4.2.1
Enabled: true
ID: textarea-cache-lite@wildsky.cc

Name: The Pirate Bay Torrent Search
Version: 0.1.7
Enabled: true
ID: {682b93a2-cb50-4363-8682-334b590efd71}

Name: TrackMeNot
Version: 0.10.46
Enabled: true
ID: trackmenot@mrl.nyu.edu

Name: Twitter
Version: 1.0
Enabled: true
ID: twitter@search.mozilla.org

Name: Undo Closed Tabs Menu
Version: 2.0
Enabled: true
ID: tst-closed_tabs_menu@dontpokebadgers.com

Name: Video Downloader Pro
Version: 1.3.9
Enabled: true
ID: @video_downloader_pro

Name: Video DownloadHelper
Version: 7.3.7
Enabled: true
ID: {b9db16a4-6edc-47ec-a1f4-b86292ed211d}

Name: Web Developer
Version: 2.0.4
Enabled: true
ID: {c45c406e-ab73-11d8-be73-000a95be3b12}

Name: Wikipedia (en)
Version: 1.0
Enabled: true
ID: wikipedia@search.mozilla.org

Name: YouTube mp3
Version: 1.0.13
Enabled: true
ID: @youtube-mp3-revised

Name: YouTube Video and Audio Downloader (Dev Edt.)
Version: 0.9.0
Enabled: true
ID: {f73df109-8fb4-453e-8373-f59e61ca4da3}

Name: YouTube Video Downloader/YouTube HD Download
Version: 1.1.0
Enabled: true
ID: youtubedownloader@youtubedownloadvideo1clickgroup.com

Name: YouTube™ No Buffer (Stop Auto-playing)
Version: 0.2.8
Enabled: true
ID: {551f032e-353d-4d10-b186-b0026b1a666d}

Name: Zoom Page WE
Version: 16.6
Enabled: true
ID: zoompage-we@DW-dev

Name: Autofill
Version: 9.5.6
Enabled: false
ID: {143f479b-4cb2-4d8c-8c31-ae8653bc6054}

Name: Don't touch my tabs! (rel=noopener)
Version: 2.1.1
Enabled: false
ID: {6b938c0c-fc53-4f27-805f-619778631082}

Name: KeePassHelper Password Manager
Version: 0.4.5
Enabled: false
ID: {69ef9498-0139-43e4-97b8-942982ac9158}

Name: KissAnime Adblocker
Version: 1.0.1
Enabled: false
ID: {dd528622-4af4-41ba-a6a2-e420b482b15f}

Name: LoadTabOnSelect Evolution
Version: 1.6
Enabled: false
ID: {18d535b1-dd41-4309-a9a5-f92699430f4f}

Name: Nuke Anything
Version: 2.4
Enabled: false
ID: {1ced4832-f06e-413f-aa14-9eb63ad40ace}

Name: Open image in a new tab
Version: 0.1
Enabled: false
ID: {7276f3bb-de56-4b5a-b940-88b62731d409}

Name: Open in new tab
Version: 0.0.12
Enabled: false
ID: {6f5f4891-9637-41f9-9ee5-3a0ac02cf254}

Name: Search by Image
Version: 2.1.0
Enabled: false
ID: {2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}

Name: Yet Another Smooth Scrolling WE
Version: 2.0.6
Enabled: false
ID: yetanothersmoothscrollingwe@kataho

Name: YouTube High Definition
Version: 68.0.2
Enabled: false
ID: {7b1bf0b6-a1b9-42b0-b75d-252036438bdc}

Name: YouTube Video Downloader - For Context Menu
Version: 0.2.1
Enabled: false
ID: jid1-KWFaW5zc0EbtBQ@jetpack

Security Software
-----------------

Type: Windows Defender Antivirus

Type:

Type: Windows Firewall

Important Modified Preferences
------------------------------

accessibility.browsewithcaret_shortcut.enabled: false
accessibility.typeaheadfind.flashBar: 0
browser.cache.disk.amount_written: 699788
browser.cache.disk.capacity: 1048576
browser.cache.disk.filesystem_reported: 1
browser.cache.disk.hashstats_reported: 1
browser.cache.disk.smart_size.first_run: false
browser.cache.disk.smart_size.use_old_max: false
browser.cache.disk.telemetry_report_ID: 68
browser.cache.frecency_experiment: 4
browser.contentblocking.category: custom
browser.display.document_color_use: 1
browser.display.show_loading_image_placeholder: true
browser.display.use_system_colors: true
browser.download.useDownloadDir: false
browser.link.open_newwindow.override.external: 3
browser.link.open_newwindow.restriction: 0
browser.places.smartBookmarksVersion: 8
browser.search.openintab: true
browser.search.useDBForOrder: true
browser.sessionstore.max_windows_undo: 5
browser.sessionstore.upgradeBackup.latestBuildID: 20200107212822
browser.startup.homepage: https://www.msn.com/en-ca?checklang=1
browser.startup.homepage_override.buildID: 20200107212822
browser.startup.homepage_override.mstone: 72.0.1
browser.tabs.closeWindowWithLastTab: false
browser.tabs.drawInTitlebar: false
browser.tabs.loadBookmarksInBackground: true
browser.tabs.remote.autostart: false
browser.tabs.remote.autostart.2: false
browser.urlbar.lastSuggestionsPromptDate: 20170831
browser.urlbar.matchBuckets: general:5,suggestion:Infinity
browser.urlbar.placeholderName: Google
browser.urlbar.placeholderName.private: Google
browser.urlbar.suggest.openpage: false
browser.urlbar.timesBeforeHidingSuggestionsHint: 0
browser.zoom.siteSpecific: false
dom.event.contextmenu.enabled: false
dom.ipc.processCount: 4
dom.ipc.processCount.web: 4
dom.popup_allowed_events: change click dblclick mouseup pointerup notificationclick reset submit touchend
dom.push.userAgentID: 09e85f37876f4d139b42e8fb77a0fd26
extensions.lastAppVersion: 72.0.1
font.internaluseonly.changed: true
font.language.group: x-armn
font.minimum-size.x-armn: 30
font.minimum-size.x-western: 14
font.name.serif.x-armn: Futura
font.size.fixed.x-western: 20
font.size.monospace.x-armn: 30
font.size.variable.x-armn: 44
font.size.variable.x-western: 26
general.autoScroll: false
gfx.crash-guard.d3d11layers.appVersion: 56.0
gfx.crash-guard.d3d11layers.deviceID: 0x00ba
gfx.crash-guard.d3d11layers.driverVersion: 10.0.17763.1
gfx.crash-guard.d3d11layers.feature-d2d: false
gfx.crash-guard.d3d11layers.feature-d3d11: false
gfx.crash-guard.d3d11video.appVersion: 67.0.2
gfx.crash-guard.d3d11video.deviceID: 0x1c82
gfx.crash-guard.d3d11video.driverVersion: 25.21.14.1891
gfx.crash-guard.status.d3d11layers: 2
gfx.crash-guard.status.d3d11video: 2
gfx.crash-guard.status.d3d9video: 2
gfx.crash-guard.status.wmfvpxvideo: 2
gfx.crash-guard.wmfvpxvideo.appVersion: 71.0
gfx.crash-guard.wmfvpxvideo.deviceID: 0x1c82
gfx.crash-guard.wmfvpxvideo.driverVersion: 26.21.14.4166
idle.lastDailyNotification: 1578542458
layers.acceleration.disabled: true
layers.mlgpu.sanity-test-failed: false
media.autoplay.enabled: false
media.benchmark.vp9.fps: 199
media.benchmark.vp9.versioncheck: 5
media.gmp-gmpopenh264.abi: x86_64-msvc-x64
media.gmp-gmpopenh264.lastUpdate: 1573587463
media.gmp-gmpopenh264.version: 1.8.1.1
media.gmp-manager.buildID: 20200107212822
media.gmp-manager.lastCheck: 1578508198
media.gmp-widevinecdm.abi: x86_64-msvc-x64
media.gmp-widevinecdm.lastUpdate: 1567765400
media.gmp-widevinecdm.version: 4.10.1440.19
media.gmp.storage.version.observed: 1
media.hardware-video-decoding.failed: false
network.cookie.prefsMigrated: true
network.dns.disableIPv6: true
network.http.pipelining: true
network.http.pipelining.maxrequests: 35
network.http.proxy.pipelining: true
network.predictor.cleaned-up: true
places.database.lastMaintenance: 1578275612
places.history.expiration.transient_current_max_pages: 78252
plugin.disable_full_page_plugin_for_types: application/pdf
plugin.flash.arch: x86_64-msvc
plugin.flash.blockliststate: 0
plugin.flash.desc: Shockwave Flash 32.0 r0
plugin.flash.lastmod_hi: 367
plugin.flash.lastmod_lo: 615492490
plugin.flash.path: C:\WINDOWS\system32\Macromed\Flash\NPSWF64_32_0_0_303.dll
plugin.flash.version: 32.0.0.303
plugin.state.flash: 2
plugins.ctprollout.cohort: user-changed-from-test
plugins.ctprollout.cohortSample: 0.074979
plugins.flashBlock.enabled: false
privacy.cpd.offlineApps: true
privacy.cpd.sessions: false
privacy.cpd.siteSettings: true
privacy.donottrackheader.enabled: true
privacy.history.custom: true
privacy.sanitize.pending: [{"id":"newtab-container","itemsToClear":[],"options":{}}]
privacy.sanitize.timeSpan: 0
privacy.socialtracking.notification.counter: 1
privacy.socialtracking.notification.enabled: false
privacy.socialtracking.notification.lastShown: 1573630584747
privacy.userContext.enabled: true
privacy.userContext.extension: {85d2532b-a793-4048-8ef4-713af1ff320d}
privacy.userContext.longPressBehavior: 2
privacy.userContext.ui.enabled: true
security.disable_button.openCertManager: false
security.disable_button.openDeviceManager: false
security.remote_settings.intermediates.checked: 1561680338
security.sandbox.content.tempDirSuffix: {ce7f09d9-5f4c-4095-8030-8e27d23b73f1}
security.sandbox.plugin.tempDirSuffix: {1a8b5f25-b83b-4873-8e0e-d2153f22a6b1}
security.ssl.enable_ocsp_stapling: false
security.ssl.errorReporting.automatic: true
services.sync.declinedEngines:
signon.importedFromSqlite: true
signon.rememberSignons: false
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1576251331
svg.context-properties.content.enabled: true
ui.osk.debug.keyboardDisplayReason: IKPOS: Touch screen not found.

**Comment by joshuacant** [comment]
I have Firefox's tab bar completely hidden and I use TST. I'll have to check and see if the extension is still working with stock Firefox tabs.

**Comment by joshuacant** [comment]
This seems to be working for me on the latest developer edition of Firefox, with a brand new empty profile. Is it possible your userchrome modifications are hiding addon-added context menu items? Webextensions are VERY limited in what they can do, so there's no way for it to even be aware of your changes, let alone do anything to them. I can make an API call to add items to context menus, and Firefox handles it from there.

![2020-01-10_01-41-47](https://user-images.githubusercontent.com/1975723/72131531-87f81380-334a-11ea-8936-049756ae6da1.png)
